### ISSUE TITLE
Saving and loading graphs on Gist

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#11]
- [x] The user can log into [Gist](gist.github.com/) from Gephi-lite
- [x] The user can see the list of graph files saved into their Gist account
- [x] The user can load a GEXF graph file from Gist
- [x] When the user is editing a graph file from Gist, a "Quick save" button becomes available, that allows them to override the Gist file by their graph file, exported as GEXF (basically: they can save their graph as a GEXF over the Gist)
- [x] User can save a graph as a public / private gist

**Comment by sim51** [comment]
## Auth 

Github doesn't support openId, only Oauth2.

### Oauth 

On Oauth, we must validate the code returned by GH, by doing a call to GH with the code, the client ID & secret token. 
Or in an SPA, the secret  token can't be ... secret.

### Device

The device code login needs to do a call to GH to retrieve the code that the user will be asked to enter on the device code page.
But when I do that with the `@octokit/auth-oauth-device` lib, I have CORS issue that can't be solve.
I also tried to do it manually with `fetch` with the mode `no-cors`, but every time I have 4XX error.

### Solutions 

- Using an external service like `https://auth0.com/` 
- Using a backend (just for the validate call)
- Using nginx with a special config that forward a dedicated endpoint to GH code validation (with the secret token) 
- Other ?

## Gist 
 
API documentation : https://docs.github.com/en/rest/gists/gists#list-gists-for-the-authenticated-user
We can't search for gists. So we have a to retrieve all the user's gists, and check if there is a file with the extension gexf
