### ISSUE TITLE
Make the tool online

### ISSUE THREAD

**Issue by pragunap2e** [gephi/gephi-lite#114]
Currently the tool is offline (i.e need to upload the file), is there a way to make it online (automatically update graph with streams of data).

**Comment by sim51** [comment]
This feature is not available.
Gephi lite is server less, everything runs on the client side. There is no way to manipulate the graph data outside the application.
By curiosity, what kind of data stream you want to use ?

**Comment by sim51** [comment]
To push data to gephi-lite is not possible (it's a webapp), but to pull data from gephi-lite by writing some code is doable.
The code you need to call is located here : https://github.com/gephi/gephi-lite/blob/main/src/core/graph/index.ts (it allow you to manage the data in graph).

But we give no guarantee that this code will not be changed in the next release. 

We planned to be able load more  graph formats in gephi-lite (ex: graphml, neo4j, json, ...), but don't know we will be able to do that.

**Comment by pragunap2e** [comment]
Thanks, I think with this graph state updates are possible based on some events after pulling data
