### ISSUE TITLE
Missing node in imported gexf

### ISSUE THREAD

**Issue by aileo** [gephi/gephi-lite#115]
I have a gexf generated from table2net and it does not load in gephi lite : "An error occurred while opening the file. Please check that the file is a valid GEXF."

The javascript console tells me it is a missing node : "Error: graphology-gexf/parser: one of your gexf file edges points to an inexisting node. Set the parser `addMissingNodes` option to `true` if you do not care."

I can't remember if I had the same problem with gephi desktop.

I wonder if gephi-lite should provide an option for this case, create missing nodes by default or this is an issue with table2net (empty cell does not generate node)

Anyway, it would be nice to have a more explicit error message in the UI.

**Comment by sim51** [comment]
Good catch.
Yes we should review some error messages in the app like this one.
And I'm agree to add the option `addMissingNodes` to the parser (we already have the option `allowUndeclaredAttributes`).

Perhaps a better approach in term of UX, is to try to load the gexf in strict mode, and if it fails, ask the user if want to proceed anyway.
