### ISSUE TITLE
Filter on Cancel Crashes the UI

### ISSUE THREAD

**Issue by pragunap2e** [gephi/gephi-lite#116]
With custom filter modal, when we click on cancel button without saving crashes the APP. Attaching a screenshot of the error.
![Screenshot from 2023-11-28 12-17-34](https://github.com/gephi/gephi-lite/assets/138557805/934ed801-f996-4f2a-aba2-243b49439573)

**Comment by sim51** [comment]
I can easily reproduce it.
Thanks for the report !
