### ISSUE TITLE
Allow importing GraphMLs

### ISSUE THREAD

**Issue by sim51** [gephi/gephi-lite#135]
It's done, but I have a question.

For github so far we allow the user to open and then save its graph file.
But in graphml we just have a parser (no writer yet).
I can allow a user to open a graphml file from github (it's easy), but for that I need to say to the user that it will be in "readonly mode" and also disable the save.

What do you think ?

**Comment by paulgirard** [comment]
For me importing means we can read not necessarily that we can write.
So Gephi Lite graph imported from a graphml file should be editable and saved in GEXF.
