### ISSUE TITLE
reset app state button

### ISSUE THREAD

**Issue by sim51** [gephi/gephi-lite#137]
When you have a graph opened in gephi-lite, and then you want to create a graph from zero, there is not way in the UI to clear everything.

The only way is to refresh the application.

**Comment by paulgirard** [comment]
The current application is not "open empty graph" but "reset app state" danger button.
This is because we have not worked on #34 yet.
We might want to be able to keep some app state while clearing the current graph.
I add this user story to #34 and rename/close this issue.
