### ISSUE TITLE
Login to Github failure

### ISSUE THREAD

**Issue by tchapeaux** [gephi/gephi-lite#144]
When trying to connect with our Github account, we see an error message

![image](https://github.com/gephi/gephi-lite/assets/1427052/1593ec0e-7d94-4d93-8860-7e412a58ffdd)

![image](https://github.com/gephi/gephi-lite/assets/1427052/e1e45ce0-abe4-4277-963f-3660527e1bcd)

How to reproduce :

1. Open Gephi Lite
2. Connect to Github

**Comment by sim51** [comment]
Thanks for the report, I can reproduce it. 
I will check that soon.
