### ISSUE TITLE
Graph data model update issues

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#148]
- [ ] run modularity use it to color and re-run with a different resolution => color settings not discarded and not in sync
- [ ] run custom script, use it in appearance, re run custom script => appearance settings not discarded and not in sync

**Comment by sim51** [comment]
* Load `Les Misérables.gexf`
* Compute a louvain metric with a resolution of 1
* Make node color base on the field `modularityClass`
* You should have a color set of size 6
* Compute a louvain metric with a resolution of 10
* Check the color set, you still have 6 values
* Set the color as `constant` and then `modularityClass`
* A new color set is generated with all the value
