### ISSUE TITLE
Boolean attributes are not rendered corectly in node panel

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#153]
![image](https://github.com/gephi/gephi-lite/assets/193478/25c996fa-e2ca-4e84-8635-9c4e52e4c3f6)

But

![image](https://github.com/gephi/gephi-lite/assets/193478/becf7ae6-73d3-4a94-804c-edc8f5eeee3f)

**Comment by sim51** [comment]
The issue is when you import a GEXF with some boolean attributs.
