### ISSUE TITLE
Graph metadata overview

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#162]
- [x] In a graph with a years attribute, checking quantitative will show a wrong value warning for no reasons
- [x] make the warning message more explicit

**Comment by sim51** [comment]
* Load a GEXF with a year property with a type string
* Go to the metadata tab
* Check that the `Qualitative` checkbox is checked for the year attribut, and not the `quantitative`
* Now, click on the  `quantitative` checkbox to enable it 
* A warning is displayed
