### ISSUE TITLE
Starting with Docker

### ISSUE THREAD

**Issue by NotYuSheng** [gephi/gephi-lite#169]
I'm having issues trying to start the project with Docker. These are the steps I followed

1. Clone this repository and navigate to project folder
```
git clone https://github.com/gephi/gephi-lite.git
cd gephi-lite
```

2. Build container
```
docker compose build
```

3. Get shell into container
```
docker compose run --entrypoint sh gephi-lite
```

4. Download dependencies
```
cd gephi-lite
npm install
```

5. Start application
```
npm start
```
Result:
```
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.12  ready in 7473 ms

  ➜  Local:   http://localhost:5173/gephi-lite
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

[TypeScript] Found 0 errors. Watching for file changes.
[ESLint] Found 0 error and 0 warning
```

However the site `http://localhost:5173/gephi-lite`  can't be reach from my host.

**Comment by sim51** [comment]
Where have you found this tuto ? 

You don't need to go inside the container ... doing a `docker compose up` is enough to start the project.
If you want to know your error, you should check the [entrypoint.sh](https://github.com/gephi/gephi-lite/blob/main/entrypoint.sh)  we used.

**Comment by NotYuSheng** [comment]
Thanks for the help, I initially ran the `entrypoint.sh` file and it resulted with a 
```
gephi-lite-1  | exec /gephi-lite/entrypoint.sh: no such file or directory
gephi-lite-1 exited with code 1
```
Since I'm running Docker from a Windows hosts, an EOL Conversion of the `entrypoint.sh` file to UNIX needs to be done.
