### ISSUE TITLE
Caption

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#21]
Gephi Lite will be able to draw a caption which explain how the visual parameters were obtained.
This data will be saved in GEXF 1.3 format which is meant to specify how to write these captions info (see https://github.com/gephi/gexf/pull/18 - our ambition is to use Gephi Lite as a test/challenge/enhance this new spec).

- [x] draw node size legend
- [x] draw node color legend
- [x] draw edge size legend
- [x] draw edge color legend
- [ ] #124

Such a caption objective is to convey information about how to read the graph.
It's not central to the use of gephi lite as a network map cartographer.
Plus it will eat a reasonable number of pixels to display information which are also partially available in the edit menus.
Thus the caption might need to be hidable or collapsible.

Application state where the cation must be visible : 

- [ ] #125
- [ ] #126

**Comment by sim51** [comment]
For color, we should add the "missing value color"
