### ISSUE TITLE
Add a translation hook/system

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#22]
Set up the translation hook is important to have the soonest.
Then decide how to manage translations.

**Comment by Yomguithereal** [comment]
I just did this on the v2 of `catwalk` using yaml files: https://github.com/medialab/catwalk/tree/v2/i18n whose type declarations are automatically generated by this script: https://github.com/medialab/catwalk/blob/v2/scripts/yaml-dts.js and then we have a basic hook relying on context and giving access to the messages in the currently selected lang: https://github.com/medialab/catwalk/blob/v2/src/hooks/context.ts

It's very simple though, but just an example.

**Comment by sim51** [comment]
Closing in favor of #18

**Comment by sim51** [comment]
Closing in favor of #18
