### ISSUE TITLE
Review generation of gexf

### ISSUE THREAD

**Issue by sim51** [gephi/gephi-lite#24]
We generate a GEXF file from the state of the application. 
You can take a look here : https://github.com/gephi/gephi-lite/blob/dev/src/core/graph/useExportAsGexf.ts#L17 

This generation should be review. For now when we generate the gexf file we don't have the visual variable on nodes (because it's done on the sigma reducer).

**Comment by jacomyal** [comment]
This has been resolved with this commit:
https://github.com/gephi/gephi-lite/commit/5c36d843169819cd38b786312e4f5f8e4bb8c615
