### ISSUE TITLE
Graph appearance block

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#5]
This UI gathers all graphical variable settings to adapt the graph renderers including its captions.

#### Node appearance

A UI which list the visual variables for nodes by partition if active (see#19).
For each partition it's possible to edit color, size, label settings (see dedicated components).

#### Edge appearance

A UI which: 
- [x]  a checkbox which allow to hide all edges which disabled all visual appearance UI for edges
- [ ] list the visual variables (size, color, labels) for edges by partition if active (see#19).

#### color component
create a UI component which allow to specify how to get one color from an attribute value.
Its props are from an attribute specification: attribute nature + attributes values index.

There are four kind of color definition: 

- quantitative: map a numeric value to a color space (defined by any gradient, with 2 to N hand-picked colors)  potentially using a transformation method (see Gexf spec)
- qualitative: pick one color to a set of existing value using a palette or picking one by one
- identity: using the attribute value as a color value
- static: using the same color for everyone (we don't need an attribute for that)

On top of this definition, the user must chose default colors which will be used for:
- incorrect values: value which can't be cast to the expected attribute nature
- undefined values: missing values

#### size component
create a UI component which allow to specifies how to get one size from an attribute value..
Its props are an attribute specification: attribute nature + attributes values index.

There are four kind of size definition: 

- quantitative: map a numeric value to a size space (defined by a range) potentially using a transformation method (see Gexf spec)
- identity: using the attribute value as a color value
- static: using the same color for everyone (we don't need an attribute for that)

On top of this definition, the user must chose default sizes which will be used for:
- incorrect values: value which can't be cast to the expected attribute nature
- undefined values: missing values

#### label component

A UI component which configures how the labels are rendered:
- [x] select any attribute which holds the label values
- [x] define a size method : follow item-size, static value (relatively to display settings)
- [ ] zoom factor : constant [0,1] follow zoom exactly
- [x] label size transformation : min-max size
- [ ] label density: threshold (0.1-10 less, more see retina) 
- [ ] chose a font
- [x] hide

#### Caption appearance

- [ ] partition label dictionaries

**Comment by Yomguithereal** [comment]
Do we want to go as far as custom splines for interpolation vs. typical handpicked options?

**Comment by jacomyal** [comment]
> Do we want to go as far as custom splines for interpolation vs. typical handpicked options?

I think we can have these features designed in a friendly enough way.
