### ISSUE TITLE
[appearance] Keep settings even when reselecting the same option in the select

### ISSUE THREAD

**Issue by sim51** [gephi/gephi-lite#50]
If I spent a long time to customize my colors  when `modularityClass as strings` is selected  , when I reselect it, the colors are regenerated, so I loast my work.

Same for the ranges on ` modularityClass as numbers`.

Same behavior on Labels & Size.

We should keep those value in the session store

**Comment by paulgirard** [comment]
We need to discuss how to store color palettes in user session.
Keeping it open for now.

**Comment by jacomyal** [comment]
I close this tickets about the bug, and I just created a new ticket (#61) about palettes management.
