### ISSUE TITLE
[layout] WHen running FA2, the 'see the whoe graph' button doesn't work 

### ISSUE THREAD

**Issue by sim51** [gephi/gephi-lite#55]
Step to reproduce : 

1. load a graph 
2. Run a random layout
3. Run a FA2 layout
4. While FA2 is running, click on the button to see the whole graph

Edit: zoom buttons are OK

**Comment by jacomyal** [comment]
OK, the reason for that is that, right now, this button uses position data from the `graphDataset` to get the new bounding boxes. And the new positions after FA2 are only saved once the user clicks the "Stop" button.
