### ISSUE TITLE
Layout block

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#6]
- [x] The user can select a layout algorithm in a select input. Choices are to pick within graphology's [standard library](https://graphology.github.io/standard-library/)
- [x] Once a layout is selected, the user can customize settings in a form below the select input. Settings can have a description, readable by the user.
- [x] A `Run` button allows user to start the layout. Deterministic layouts will instantly stop, but iterative layouts will keep running until they auto-stop or the user clicks `Stop`.
- [x] By default, FA2 with inferred settings is selected, so that a single click can start the (most commonly chosen) layout
- [ ] In the list of options, the user can select "Custom script" which opens a modal with a text area where they can write a JavaScript function that takes a copy of each node and a copy of the graph and should return `{ x: number, y:number }`

**Comment by Yomguithereal** [comment]
We should preload the chosen layout to be FA2 with typical settings as a default so that a single button click should be enough to trigger a basic layout, no?

**Comment by jacomyal** [comment]
Agreed
