### ISSUE TITLE
Improve state management

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#62]
There are right now multiple level of "memories": Some things are stored in local storage, some in session storage, some might be in URL query later etc...

Also, there are some things that are not "remembered" yet that should probably be in the future:
- Color palettes (see #61)
- Last selected layout or metric
- Selections ? (could / should there be an "undo/redo" of selection?)

**Comment by paulgirard** [comment]
The graph is stored in local storage. What If I want to wipe that? In current version it's not possible from Gephi lite.
Which means create a new empty graph is just impossible without clearing storage from the web browser.

**Comment by sim51** [comment]
FYI, adding `?new` in the url clear data related to the graph.

**Comment by paulgirard** [comment]
I forgot about that! Well adding a simple link to ?new in the file tab would solve my issue.
