### ISSUE TITLE
Can't open this local gexf graph

### ISSUE THREAD

**Issue by seinecle** [gephi/gephi-lite#64]
Not sure why? I just use the "open file" interface, select the file and load.

File (change .txt to gexf)
[seinecle.txt](https://github.com/gephi/gephi-lite/files/11149867/seinecle.txt)

Error message:

![image](https://user-images.githubusercontent.com/1244100/229830339-e890a3c2-4cce-4287-8d02-1e30465cc389.png)

**Comment by jacomyal** [comment]
@seinecle The fix has properly been deployed. You can clear your browser's cache, reload the page and try again. Thanks again!

**Comment by seinecle** [comment]
Great it works, thanks!
