### ISSUE TITLE
Context block

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#7]
Context block shows information about the graph:

- [x] Title of the graph
- [x] Nodes and edges counts
- [x] When filters are active, visible nodes and edges counts and percentages

It then displays data about the current selection:

- [x] When no node is selected, a message saying `No item selected yet` is displayed
- [ ] When the selection is just one node, it appears as a node similar to the ones on the graph, but with its attributes list bellow
- [ ] When the selection is just one edge, it appears as a node similar to the ones on the graph, but with its attributes list bellow
- [ ] When multiple nodes and/or edges are selected, they appear as a list of items similar to the ones on the graph
- [ ] The list of contextual actions are displayed then:
  - [ ] Select all
  - [ ] Empty selection
  - [ ] Delete selection
  - [ ] Edit selection attributes (if they are of only one type)
  - [ ] Edit selected item attributes (in a different form, that displays current attributes of the item)

**Comment by Yomguithereal** [comment]
Should we add density? Or at least a sense of density (graph is sparse, quite sparse, rather dense etc.). It is often useful in projection scenarios and hairballs etc.
