### ISSUE TITLE
Recognize automatically URL when displaying attributes in node panel

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#73]
User needs: be able to click on URL to consult remote content when selecting one node and seeing node attributes

Solution possible:
- in node panel for attribute which are marked as qualitative detect URL and enclosed them in <a> tags?

**Comment by jacomyal** [comment]
For the record, here is how it's done in Retina:
https://gitlab.com/ouestware/retina/-/blob/main/src/views/SelectedNodePanel.tsx?ref_type=heads#L46
