### ISSUE TITLE
show edges does not work

### ISSUE THREAD

**Issue by paulgirard** [gephi/gephi-lite#89]
![image](https://github.com/gephi/gephi-lite/assets/193478/9cb0789e-e831-40ac-9ed0-31faf84d8007)

**Comment by Splines** [comment]
This is still an issue for me (Brave-browser, chromium-based). If I uncheck `Show edges`, edges still show up in the graph. Can even reproduce with the sample file like `Les Miserables.gexf`.

**Comment by paulgirard** [comment]
indeed...
