### ISSUE TITLE
"Some" end-to-end tests

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#93]

**Comment by sim51** [comment]
Using playwright from m$

You can exec `npm run test:e2e` to run the end to end test. 

If you have updated the project style/layout, you will have to delete the saved screenshot in `/e2e/*.spec.ts-snapthots/*`, and then run the e2e test to regenerate them.

For the rest, see https://playwright.dev/

**Comment by paulgirard** [comment]
I added information about e2e in the readme
